services:
  fs-api:
    image: file-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@fs-db:5432/postgres
      - STORAGE_PATH=/storage
    volumes:
      - ./docker/fs-api-storage:/storage
    depends_on:
      fs-db:
        condition: service_healthy

  fs-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker/fs-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
