// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/file.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ViewFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFilesRequest) Reset() {
	*x = ViewFilesRequest{}
	mi := &file_api_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFilesRequest) ProtoMessage() {}

func (x *ViewFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFilesRequest.ProtoReflect.Descriptor instead.
func (*ViewFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{2}
}

func (x *ViewFilesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ViewFilesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ViewFilesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Files         []*ViewFilesResponse_FileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFilesResponse) Reset() {
	*x = ViewFilesResponse{}
	mi := &file_api_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFilesResponse) ProtoMessage() {}

func (x *ViewFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFilesResponse.ProtoReflect.Descriptor instead.
func (*ViewFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{3}
}

func (x *ViewFilesResponse) GetFiles() []*ViewFilesResponse_FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_api_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_api_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ViewFilesResponse_FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFilesResponse_FileInfo) Reset() {
	*x = ViewFilesResponse_FileInfo{}
	mi := &file_api_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFilesResponse_FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFilesResponse_FileInfo) ProtoMessage() {}

func (x *ViewFilesResponse_FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFilesResponse_FileInfo.ProtoReflect.Descriptor instead.
func (*ViewFilesResponse_FileInfo) Descriptor() ([]byte, []int) {
	return file_api_file_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ViewFilesResponse_FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ViewFilesResponse_FileInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ViewFilesResponse_FileInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_file_proto protoreflect.FileDescriptor

const file_api_file_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/file.proto\x12\x04file\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"-\n" +
	"\x12UploadFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"@\n" +
	"\x10ViewFilesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"\xea\x01\n" +
	"\x11ViewFilesResponse\x126\n" +
	"\x05files\x18\x01 \x03(\v2 .file.ViewFilesResponse.FileInfoR\x05files\x1a\x9c\x01\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\".\n" +
	"\x13DownloadFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"F\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xd3\x01\n" +
	"\vFileService\x12?\n" +
	"\n" +
	"UploadFile\x12\x17.file.UploadFileRequest\x1a\x18.file.UploadFileResponse\x12<\n" +
	"\tViewFiles\x12\x16.file.ViewFilesRequest\x1a\x17.file.ViewFilesResponse\x12E\n" +
	"\fDownloadFile\x12\x19.file.DownloadFileRequest\x1a\x1a.file.DownloadFileResponseB\x10Z\x0e./internal/apib\x06proto3"

var (
	file_api_file_proto_rawDescOnce sync.Once
	file_api_file_proto_rawDescData []byte
)

func file_api_file_proto_rawDescGZIP() []byte {
	file_api_file_proto_rawDescOnce.Do(func() {
		file_api_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_file_proto_rawDesc), len(file_api_file_proto_rawDesc)))
	})
	return file_api_file_proto_rawDescData
}

var file_api_file_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_file_proto_goTypes = []any{
	(*UploadFileRequest)(nil),          // 0: file.UploadFileRequest
	(*UploadFileResponse)(nil),         // 1: file.UploadFileResponse
	(*ViewFilesRequest)(nil),           // 2: file.ViewFilesRequest
	(*ViewFilesResponse)(nil),          // 3: file.ViewFilesResponse
	(*DownloadFileRequest)(nil),        // 4: file.DownloadFileRequest
	(*DownloadFileResponse)(nil),       // 5: file.DownloadFileResponse
	(*ViewFilesResponse_FileInfo)(nil), // 6: file.ViewFilesResponse.FileInfo
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_api_file_proto_depIdxs = []int32{
	6, // 0: file.ViewFilesResponse.files:type_name -> file.ViewFilesResponse.FileInfo
	7, // 1: file.ViewFilesResponse.FileInfo.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: file.ViewFilesResponse.FileInfo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: file.FileService.UploadFile:input_type -> file.UploadFileRequest
	2, // 4: file.FileService.ViewFiles:input_type -> file.ViewFilesRequest
	4, // 5: file.FileService.DownloadFile:input_type -> file.DownloadFileRequest
	1, // 6: file.FileService.UploadFile:output_type -> file.UploadFileResponse
	3, // 7: file.FileService.ViewFiles:output_type -> file.ViewFilesResponse
	5, // 8: file.FileService.DownloadFile:output_type -> file.DownloadFileResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_file_proto_init() }
func file_api_file_proto_init() {
	if File_api_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_file_proto_rawDesc), len(file_api_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_file_proto_goTypes,
		DependencyIndexes: file_api_file_proto_depIdxs,
		MessageInfos:      file_api_file_proto_msgTypes,
	}.Build()
	File_api_file_proto = out.File
	file_api_file_proto_goTypes = nil
	file_api_file_proto_depIdxs = nil
}
